properties:
  property_1: "Default value"

backend: https://uat.polidea.com
districs:
 - Praga
 - Wola
device:
  connect:
    ip: 192.168.1.3
    port: 9876
  critical_battery_level: 5
debug_credentials:
  - name: userA
    pass: Kabum1
  - name: userB
    pass: Kabum2